### PR TITLE
Specify field when querying database for user on login

### LINKED ISSUE #24: Login authentication doesn't work
Problem with password comparison

### PR DESCRIPTION
**Pull request by ealitten**
Closes #24

### CODE REVIEW

**Comment by ealitten** [comment]
Added test test for signing in with multiple users in db, to prevent issue 24 happening again

File: spec/features/signin_spec.rb [hunk 1]
```diff
@@ -1,22 +1,26 @@
...
+  scenario 'when user does not exist' do
+    login
     expect(page).to have_content('Username or password is incorrect')
   end
 
+  scenario 'with multiple users in database' do
+    sign_up(name: 'User1', email: 'user1@example.com')
+    sign_up(name: 'User2', email: 'user1@example.com')
+    login(name: 'User1')
+    expect(page).to have_content('Welcome User1')
```
Comment (jenniferemshepherd) [inline spec/features/signin_spec.rb]: i would like to test not the first item on the database just in case.
e.g. testing user 2 as they have been added second.

Comment (jenniferemshepherd) [reply spec/features/signin_spec.rb]: we can probs test this in the same test.

Comment (ealitten) [reply spec/features/signin_spec.rb]: Done

**Comment by jenniferemshepherd** [comment]
:shipit:

**Comment by ealitten** [comment]
Simon also says :shipit:
